CREATE TABLE dados (
	dado_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	ano INTEGER NOT NULL,
	valor REAL NOT NULL,
	pais_id INTEGER NOT NULL,
	indicador_id INTEGER NOT NULL,
	FOREIGN KEY (pais_id) REFERENCES paises (pais_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (indicador_id) REFERENCES indicadores (indicador_id) ON DELETE CASCADE ON UPDATE CASCADE
);
